import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="min-h-screen bg-gray-50">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center min-h-screen py-2">
        <h1 className="text-6xl font-bold text-gray-900 mb-4">
          Welcome to{" "}
          <span className="text-blue-600 hover:underline">Next.js!</span>
        </h1>

        <p className="text-xl text-gray-600 text-center max-w-2xl mb-8">
          Get started by editing{" "}
          <code className="bg-gray-100 rounded p-1 font-mono text-sm">
            pages/index.tsx
          </code>
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-4xl w-full">
          <a
            href="https://nextjs.org/docs"
            className="p-6 border border-gray-200 rounded-lg hover:border-blue-500 hover:text-blue-600 transition-colors"
          >
            <h2 className="text-2xl font-semibold mb-2">Documentation &rarr;</h2>
            <p className="text-gray-600">
              Find in-depth information about Next.js features and API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn"
            className="p-6 border border-gray-200 rounded-lg hover:border-blue-500 hover:text-blue-600 transition-colors"
          >
            <h2 className="text-2xl font-semibold mb-2">Learn &rarr;</h2>
            <p className="text-gray-600">
              Learn about Next.js in an interactive course with quizzes!
            </p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className="p-6 border border-gray-200 rounded-lg hover:border-blue-500 hover:text-blue-600 transition-colors"
          >
            <h2 className="text-2xl font-semibold mb-2">Examples &rarr;</h2>
            <p className="text-gray-600">
              Discover and deploy boilerplate example Next.js projects.
            </p>
          </a>

          <a
            href="https://docs.replit.com/category/deployments"
            className="p-6 border border-gray-200 rounded-lg hover:border-blue-500 hover:text-blue-600 transition-colors"
          >
            <h2 className="text-2xl font-semibold mb-2">Deploy &rarr;</h2>
            <p className="text-gray-600">
              After you are happy with this app, deploy it on Replit!
            </p>
          </a>
        </div>
      </main>
    </div>
  );
};

export default Home;
