-- Insert common countries
INSERT INTO countries (code, name, region, is_high_risk, sanctions_list) VALUES
('GB', 'United Kingdom', 'Europe', false, false),
('US', 'United States', 'North America', false, false),
('FR', 'France', 'Europe', false, false),
('DE', 'Germany', 'Europe', false, false),
('ES', 'Spain', 'Europe', false, false),
('IT', 'Italy', 'Europe', false, false),
('CA', 'Canada', 'North America', false, false),
('AU', 'Australia', 'Oceania', false, false),
('NZ', 'New Zealand', 'Oceania', false, false),
('IE', 'Ireland', 'Europe', false, false),
('NL', 'Netherlands', 'Europe', false, false),
('BE', 'Belgium', 'Europe', false, false),
('CH', 'Switzerland', 'Europe', false, false),
('SE', 'Sweden', 'Europe', false, false),
('NO', 'Norway', 'Europe', false, false),
('DK', 'Denmark', 'Europe', false, false),
('FI', 'Finland', 'Europe', false, false),
('AT', 'Austria', 'Europe', false, false),
('PL', 'Poland', 'Europe', false, false),
('JP', 'Japan', 'Asia', false, false),
('KR', 'South Korea', 'Asia', false, false),
('SG', 'Singapore', 'Asia', false, false),
('HK', 'Hong Kong', 'Asia', false, false),
('IN', 'India', 'Asia', false, false),
('BD', 'Bangladesh', 'Asia', false, false),
('PK', 'Pakistan', 'Asia', false, false),
('KE', 'Kenya', 'Africa', false, false),
('UG', 'Uganda', 'Africa', false, false),
('TZ', 'Tanzania', 'Africa', false, false),
('GH', 'Ghana', 'Africa', false, false),
('NG', 'Nigeria', 'Africa', false, false),
('ZA', 'South Africa', 'Africa', false, false),
('EG', 'Egypt', 'Africa', false, false),
('MA', 'Morocco', 'Africa', false, false),
('BR', 'Brazil', 'South America', false, false),
('MX', 'Mexico', 'North America', false, false),
('AR', 'Argentina', 'South America', false, false),
('CL', 'Chile', 'South America', false, false),
('PE', 'Peru', 'South America', false, false),
('CO', 'Colombia', 'South America', false, false),
-- High-risk countries
('AF', 'Afghanistan', 'Asia', true, true),
('SY', 'Syria', 'Middle East', true, true),
('YE', 'Yemen', 'Middle East', true, false),
('SO', 'Somalia', 'Africa', true, false),
('SD', 'Sudan', 'Africa', true, false),
('IR', 'Iran', 'Middle East', true, true),
('KP', 'North Korea', 'Asia', true, true),
('MM', 'Myanmar', 'Asia', true, false),
('LY', 'Libya', 'Africa', true, false),
('VE', 'Venezuela', 'South America', true, false);